name: CI base para Projeto de Fraude (Exemplo)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 3. Install Poetry
        run: pipx install poetry

      - name: 4. Set up Poetry environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: 5. Install dependencies
        run: poetry install

      - name: 6. Run Black code formatter
        run: poetry run black --check

      - name: 7. Run Pylint
        run: poetry run pylint src/fundamentos_engenharia_software tests --fail-under=8.0

      - name: 8. Run Pylint
        run: poetry run pylint src/ tests --fail-under=8.0

      - name: 9. Run tests with pytest
        run: poetry run pytest tests/